### ISSUE TITLE
DType comparisons return Python bools instead of Numpy bools

### ISSUE THREAD

**Issue by colehaus** [jax-ml/ml_dtypes#105]
See the following example showing behavior for `bfloat16` from this library vs behavior for `float32` from Numpy:
```py
>>> import ml_dtypes
>>> type(ml_dtypes.bfloat16(1) == ml_dtypes.bfloat16(1))
<class 'bool'>
>>> import numpy as np
>>> type(np.float32(1) == np.float32(1))
<class 'numpy.bool_'>
>>> ml_dtypes.__version__
'0.2.0'
```
It looks like this is the line leading to this behavior:

https://github.com/jax-ml/ml_dtypes/blob/bbeedd470ecac727c42e97648c0f27bfc312af30/ml_dtypes/_src/custom_float.h#L351

This is not strictly a bug but seems like it might be contrary to JAX's ["tries to follow the NumPy API as closely as possible"](https://jax.readthedocs.io/en/latest/jax.numpy.html) goal.

See https://github.com/patrick-kidger/equinox/pull/511#discussion_r1337815340 for more context on how this issue was initially encountered.

Thanks!

**Comment by jakevdp** [comment]
Thanks for the report! I'll take a look.

**Comment by jakevdp** [comment]
It looks like this happens in numpy because scalar comparison is done by casting to array: https://github.com/numpy/numpy/blob/eabefa4e041617d4fcd867a147aef15189f1de56/numpy/core/src/multiarray/scalartypes.c.src#L1286

For things like `np.float32(1) == None`, though, the result is a python bool rather than a numpy bool: https://github.com/numpy/numpy/blob/eabefa4e041617d4fcd867a147aef15189f1de56/numpy/core/src/multiarray/scalartypes.c.src#L1275-L1282

I might try doing the same to see if it works, versus handing all the RichCompare op codes individually at the C-scalar level.

**Comment by colehaus** [comment]
Thanks!
